### ISSUE TITLE
Error while running the tests

### ISSUE THREAD

**Issue by szabgab** [RainbowPonny/ruby-request-builder#1]
I cloned the repo and tried:

```
./bin/setup
rake spec
```

got this error:

```
/usr/bin/ruby3.0 -I/var/lib/gems/3.0.0/gems/rspec-support-3.11.1/lib:/var/lib/gems/3.0.0/gems/rspec-core-3.11.0/lib /var/lib/gems/3.0.0/gems/rspec-core-3.11.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
/opt/lib/request/builder/request_config.rb:102: warning: key :body is duplicated and overwritten on line 113
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!

An error occurred while loading ./spec/request/builder/result_spec.rb.
Failure/Error: @config ||= conf.deep_dup || RequestConfig.new

NoMethodError:
  undefined method `deep_dup' for nil:NilClass
# ./lib/request/builder/dsl.rb:15:in `config'
# ./lib/request/builder/dsl.rb:19:in `configure'
# ./spec/request/builder/result_spec.rb:5:in `<class:TestApiResult>'
# ./spec/request/builder/result_spec.rb:2:in `block in <top (required)>'
# ./spec/request/builder/result_spec.rb:1:in `<top (required)>'

An error occurred while loading ./spec/request/builder_spec.rb.
Failure/Error: @config ||= conf.deep_dup || RequestConfig.new

NoMethodError:
  undefined method `deep_dup' for nil:NilClass
# ./lib/request/builder/dsl.rb:15:in `config'
# ./lib/request/builder/dsl.rb:19:in `configure'
# ./spec/request/builder_spec.rb:11:in `<class:TestApi>'
# ./spec/request/builder_spec.rb:2:in `block in <top (required)>'
# ./spec/request/builder_spec.rb:1:in `<top (required)>'
No examples found.

Finished in 0.00005 seconds (files took 0.39408 seconds to load)
0 examples, 0 failures, 2 errors occurred outside of examples

/usr/bin/ruby3.0 -I/var/lib/gems/3.0.0/gems/rspec-support-3.11.1/lib:/var/lib/gems/3.0.0/gems/rspec-core-3.11.0/lib /var/lib/gems/3.0.0/gems/rspec-core-3.11.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

```
bundler --version
Bundler version 2.1.4

rake --version
rake, version 13.0.6

ruby --version
ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux-gnu]
```

Running on an Ubuntu 22.10 based Docker container.

**Comment by szabgab** [comment]
it seems that a954ffd introduced this error
